import APSRecComp
import APSRecComp.SmnTracking
import APSRecComp.SmnSectionSurjectivity
import APSRecComp.FiniteTracking
import APSRecComp.SmnReachability
import APSRecComp.ConditionalNecessity
import APSMinimalInterface.Indexed
import APSMinimalInterface.InterfaceLattice

/-!
# Clone Dictionary for smn — Workstream A

Translate APS notions into clone-theoretic / universal-algebraic terms.

## The smn-generated operation system

The smn_spec law φ(smn e x)(n) = φ e (pair x n) generates an operation system:
- **Projection/specialization:** For each x₀ : ℕ, the map e ↦ smn(e, x₀) sends indices to
  "x₀-sections" — functions n ↦ φ_e(pair(x₀, n)).
- **Term operations:** Built from constants (representable indices), pairing, and specialization.

## Dictionary

| APS notion | Clone-theoretic analogue |
|------------|--------------------------|
| I_comp | Surjectivity of smn-clone onto representable unary maps |
| SmnSectionSurjectiveAt(x₀) | Surjectivity of projection/specialization at x₀ |
| Finite tracking | Local interpolation in the clone |
| SmnReachable | In the image of the clone's "application" operation |
-/

namespace APSUniformization

open Nat
open APSMinimalInterface
open APSRecComp

/-! ## Clone-theoretic definitions -/

/-- **Projection at x₀:** The map e ↦ smn(e, x₀). In clone theory, this is the
    specialization/projection that selects the x₀-section of index e.
    The x₀-section of e computes n ↦ φ_e(pair(x₀, n)). -/
def smnProjectionAt (aps : IndexedAPS) (x₀ : ℕ) (e : ℕ) : ℕ :=
  aps.smn e x₀

/-- **Extensional equality of indices** (same partial function). -/
def ExtEq (aps : IndexedAPS) (e₁ e₂ : ℕ) : Prop :=
  ∀ n, aps.φ e₁ n = aps.φ e₂ n

/-- **Projection surjective at x₀:** The projection e ↦ smn(e, x₀) is surjective
    onto extensional classes. Equivalently: for every target index e, there exists
    k with smn(k, x₀) extensionally equal to e.
    This is exactly SmnSectionSurjectiveAt. -/
def ProjectionSurjectiveAt (aps : IndexedAPS) (x₀ : ℕ) : Prop :=
  ∀ e, ∃ k, ExtEq aps (aps.smn k x₀) e

/-- **Smn term operation (unary):** An operation of the form e ↦ smn(c, e) for some
    constant c. These are the "specialization" operations generated by smn_spec.
    The full clone would include compositions; we start with the primitive. -/
def SmnTermOperation (aps : IndexedAPS) (c : ℕ) : ℕ → ℕ :=
  fun x => aps.smn c x

/-- **SmnCloneReachable:** A function g is reachable by the smn-clone if there exists
    a "term" (index k) whose smn-family tracks g. Same as SmnReachable. -/
def SmnCloneReachable (aps : IndexedAPS) (g : ℕ → ℕ) : Prop :=
  SmnReachable aps g

/-- **Local interpolation at F:** For finite F, a tracker k satisfies
    ∀ x ∈ F, smn(k, x) ≃ h₀(x). This is "local" agreement: k's sections at F
    match h₀ on F. -/
def LocalInterpolatesAt (aps : IndexedAPS) (h₀ : ℕ → ℕ) (k : ℕ) (F : Finset ℕ) : Prop :=
  ∀ x ∈ F, ∀ n, aps.φ (aps.smn k x) n = aps.φ (h₀ x) n

/-- **FiniteSmnInterpolable:** For every representable h₀ and finite F, there exists
    k that locally interpolates. This is HasFiniteTracking. -/
def FiniteSmnInterpolable (aps : IndexedAPS) : Prop :=
  HasFiniteTracking aps

/-- **SmnCloneInterpolates (global):** The clone has global interpolation for h₀:
    ∃ k, ∀ x n, smn(k, x) ≃ h₀(x). This is SmnTracks / SmnReachable. -/
def SmnCloneInterpolates (aps : IndexedAPS) (h₀ : ℕ → ℕ) : Prop :=
  SmnReachable aps h₀

/-! ## Tier 1 Theorem 1: clone_dictionary_for_smn -/

/-- **I_comp as clone surjectivity:** I_comp is equivalent to the smn-clone being
    surjective onto all representable unary maps — every representable function
    is reachable (has a tracker). -/
theorem I_comp_as_clone_surjectivity (aps : IndexedAPS) :
    HasICompIndexed aps ↔
    ∀ (h : ℕ → ℕ), IndexedRepresentableUnary aps h → SmnCloneReachable aps h :=
  (I_comp_iff_all_rep_reachable aps).trans (by rfl)

/-! ## Tier 1 Theorem 2: finite_tracking_as_local_interpolation -/

/-- **Finite tracking as local clone interpolation:** HasFiniteTracking is exactly
    FiniteSmnInterpolable — for every representable h₀ and finite F, there exists
    k whose smn-sections at F match h₀ on F. -/
theorem finite_tracking_as_local_interpolation (aps : IndexedAPS) :
    HasFiniteTracking aps ↔ FiniteSmnInterpolable aps :=
  Iff.rfl

/-- **Singleton tracking as local interpolation at {x₀}.** -/
theorem singleton_tracking_as_local_at_singleton (aps : IndexedAPS) (h₀ : ℕ → ℕ) (k x₀ : ℕ) :
    SingletonTracks aps h₀ k x₀ ↔ LocalInterpolatesAt aps h₀ k {x₀} := by
  constructor
  · intro hk x hx
    simp only [Finset.mem_singleton] at hx
    rw [hx]
    exact hk
  · intro hk n
    exact hk x₀ (Finset.mem_singleton_self x₀) n

/-- **Section surjectivity at x₀ implies local interpolation at {x₀} for any h₀.** -/
theorem section_surj_implies_local_interpolation (aps : IndexedAPS) (h₀ : ℕ → ℕ) (x₀ : ℕ)
    (h_surj : SmnSectionSurjectiveAt aps x₀) :
    ∃ k, LocalInterpolatesAt aps h₀ k {x₀} := by
  obtain ⟨k, hk⟩ := h_surj (h₀ x₀)
  exact ⟨k, fun x hx n => by simp only [Finset.mem_singleton] at hx; rw [hx]; exact hk n⟩

/-! ## Tier 1 Theorem 3: section_surj_as_projection_surj -/

/-- **SmnSectionSurjectiveAt as projection surjectivity:** Section surjectivity at x₀
    is exactly surjectivity of the clone's projection/specialization map at x₀
    onto extensional classes. -/
theorem section_surj_as_projection_surj (aps : IndexedAPS) (x₀ : ℕ) :
    SmnSectionSurjectiveAt aps x₀ ↔ ProjectionSurjectiveAt aps x₀ := by
  constructor
  · intro h e
    obtain ⟨k, hk⟩ := h e
    exact ⟨k, fun n => hk n⟩
  · intro h e
    obtain ⟨k, hk⟩ := h e
    exact ⟨k, fun n => hk n⟩

/-- **Uniform section surjectivity = projection surjective at all points.** -/
theorem uniform_section_surj_iff_projection_surj_everywhere (aps : IndexedAPS) :
    UniformSmnSectionSurjective aps ↔ ∀ x₀, ProjectionSurjectiveAt aps x₀ := by
  constructor
  · intro h x₀
    rw [← section_surj_as_projection_surj]
    exact h x₀
  · intro h x₀
    rw [section_surj_as_projection_surj]
    exact h x₀

/-! ## Algebraic dictionary summary -/

/-- **Clone dictionary summary:** The three key equivalences:
    1. I_comp ↔ clone surjective onto representable maps
    2. Finite tracking ↔ finite local interpolation
    3. Section surjectivity at x₀ ↔ projection surjective at x₀ -/
theorem clone_dictionary_for_smn (aps : IndexedAPS) :
    (HasICompIndexed aps ↔ ∀ h, IndexedRepresentableUnary aps h → SmnCloneReachable aps h) ∧
    (HasFiniteTracking aps ↔ FiniteSmnInterpolable aps) ∧
    (∀ x₀, SmnSectionSurjectiveAt aps x₀ ↔ ProjectionSurjectiveAt aps x₀) := by
  exact ⟨I_comp_as_clone_surjectivity aps,
         finite_tracking_as_local_interpolation aps,
         fun x₀ => section_surj_as_projection_surj aps x₀⟩

end APSUniformization
